import type { Job } from "@/types";
import { evaluateJobMatch } from "./matchingEngine";
import { classifyLocation } from "./locationClassifier";
import { defaultSearchProfile } from "@/config/defaultProfile";
import { calculateOpportunityPriority, getOpportunityPriorityReasons } from "./marketRadar";

const rawDemoJobs: Array<
  Omit<
    Job,
    | "match"
    | "normalizedTitle"
    | "normalizedCompany"
    | "normalizedLocation"
    | "actualJobTechnologies"
    | "matchedTargetTechnologies"
    | "technologyMatchDetails"
    | "domains"
    | "domainMatches"
    | "careerFit"
  >
> = [
  {
    id: "demo-job-001",
    title: "Senior Technical Lead - Digital Experience & Headless",
    company: "EPAM Systems (Demo)",
    location: "Hyderabad, India",
    rawLocation: "Hyderabad, India",
    remoteType: "HYBRID",
    isIndiaEligible: true,
    indiaEligibilityReason: "Location is within India (Hyderabad)",
    salaryState: "SALARY_RANGE",
    salaryMin: 3800000,
    salaryMax: 4800000,
    currency: "INR",
    salaryLpaMin: 38,
    salaryLpaMax: 48,
    salaryDisclosed: true,
    originalSalary: "₹38L – ₹48L PA",
    originalCurrency: "INR",
    isSalaryEstimated: false,
    seniority: "LEAD",
    seniorityEvidence: "Senior Technical Lead title (12+ yrs exp)",
    experienceMin: 12,
    experienceMax: 16,
    skills: ["React", "Next.js", "TypeScript", "Contentful", "Headless CMS", "GraphQL"],
    roleFamily: "TECHNICAL_LEAD",
    secondaryRoleFamilies: ["CMS_DIGITAL_EXPERIENCE"],
    travel: {
      type: "INTERNATIONAL_TRAVEL",
      percentage: 20,
      percentageRange: "10-20%",
      destinations: ["USA", "Europe"],
      evidence: "International travel required (15-20%) for client workshops in USA & Switzerland.",
      notes: "International travel required (15-20%) for client workshops in USA & Switzerland.",
      rawMention: "20% international travel to US client sites",
    },
    description:
      "Looking for a Senior Technical Lead to architect headless CMS solutions using Next.js and Contentful for Global 500 clients. Involves cross-border architecture alignment and client visits.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-001",
    postedAt: "2026-09-23T10:00:00Z",
    discoveredAt: "2026-09-24T06:00:00Z",
    lastVerifiedAt: "2026-09-24T06:00:00Z",
    freshness: "FRESH",
    postedDaysAgo: 1,
    status: "DISCOVERED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-002",
    title: "Frontend Architect - Commerce & Micro-frontends",
    company: "Publicis Sapient (Demo)",
    location: "Hyderabad / Bengaluru",
    rawLocation: "Hyderabad / Bengaluru",
    remoteType: "HYBRID",
    isIndiaEligible: true,
    indiaEligibilityReason: "Location is within India (Hyderabad/Bengaluru)",
    salaryState: "SALARY_RANGE",
    salaryMin: 4200000,
    salaryMax: 5200000,
    currency: "INR",
    salaryLpaMin: 42,
    salaryLpaMax: 52,
    salaryDisclosed: true,
    originalSalary: "₹42L – ₹52L PA",
    originalCurrency: "INR",
    isSalaryEstimated: false,
    seniority: "ARCHITECT",
    seniorityEvidence: "Frontend Architect title (12+ yrs exp)",
    experienceMin: 12,
    experienceMax: 18,
    skills: ["React", "TypeScript", "Next.js", "Frontend Architecture", "Commerce"],
    roleFamily: "FRONTEND_ARCHITECT",
    secondaryRoleFamilies: ["COMMERCE"],
    travel: {
      type: "INTERNATIONAL_TRAVEL",
      percentage: 25,
      percentageRange: "20-30%",
      destinations: ["Middle East", "Europe"],
      evidence: "International project travel to Dubai and London customer headquarters up to 25%.",
      notes: "International project travel to Dubai and London customer headquarters.",
      rawMention: "25% travel to Middle East & UK",
    },
    description:
      "Enterprise digital experience leader seeking a Frontend Architect for composable commerce and digital experience platforms. Lead high-performance engineering teams and advise C-level client stakeholders.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-002",
    postedAt: "2026-09-22T08:30:00Z",
    discoveredAt: "2026-09-24T05:30:00Z",
    lastVerifiedAt: "2026-09-24T05:30:00Z",
    freshness: "FRESH",
    postedDaysAgo: 2,
    status: "SAVED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-003",
    title: "Solutions Architect - Modern Web & Headless CMS",
    company: "Thoughtworks (Demo)",
    location: "Remote India",
    rawLocation: "Remote India",
    remoteType: "REMOTE",
    isIndiaEligible: true,
    indiaEligibilityReason: "Explicitly designated as India Remote",
    salaryState: "SALARY_RANGE",
    salaryMin: 4000000,
    salaryMax: 5000000,
    currency: "INR",
    salaryLpaMin: 40,
    salaryLpaMax: 50,
    salaryDisclosed: true,
    originalSalary: "₹40L – ₹50L PA",
    originalCurrency: "INR",
    isSalaryEstimated: false,
    seniority: "ARCHITECT",
    seniorityEvidence: "Solutions Architect title",
    experienceMin: 11,
    experienceMax: 16,
    skills: ["React", "Angular", "TypeScript", "Contentful", "Design Systems", "Node.js"],
    roleFamily: "SOLUTIONS_ARCHITECT",
    secondaryRoleFamilies: ["CMS_DIGITAL_EXPERIENCE"],
    travel: {
      type: "CLIENT_SITE_TRAVEL",
      percentage: 15,
      percentageRange: "10-20%",
      destinations: ["Singapore", "Australia"],
      evidence: "Client-site travel for quarterly architecture review sprints in Singapore (15%).",
      notes: "Client-site travel for quarterly architecture review sprints in Singapore.",
      rawMention: "Quarterly travel to Singapore",
    },
    description:
      "Drive architecture design for modern digital transformation initiatives. Guide cross-functional squads in adopting MACH principles and headless digital experience architectures.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-003",
    postedAt: "2026-09-21T14:15:00Z",
    discoveredAt: "2026-09-24T04:00:00Z",
    lastVerifiedAt: "2026-09-24T04:00:00Z",
    freshness: "FRESH",
    postedDaysAgo: 3,
    status: "APPLIED",
    appliedAt: "2026-09-23T11:00:00Z",
    notes: "Applied via referral through senior director. Portfolio shared.",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-004",
    title: "CMS & Digital Experience Consultant",
    company: "Valtech (Demo)",
    location: "Hyderabad / Remote",
    rawLocation: "Hyderabad / Remote",
    remoteType: "REMOTE",
    isIndiaEligible: true,
    indiaEligibilityReason: "Location includes Hyderabad / India Remote",
    salaryState: "SALARY_RANGE",
    salaryMin: 3600000,
    salaryMax: 4600000,
    currency: "INR",
    salaryLpaMin: 36,
    salaryLpaMax: 46,
    salaryDisclosed: true,
    originalSalary: "₹36L – ₹46L PA",
    originalCurrency: "INR",
    isSalaryEstimated: false,
    seniority: "SENIOR",
    seniorityEvidence: "Senior consultant with 10+ yrs exp",
    experienceMin: 10,
    experienceMax: 15,
    skills: ["Contentful", "Headless CMS", "React", "Next.js", "Commerce"],
    roleFamily: "CMS_DIGITAL_EXPERIENCE",
    secondaryRoleFamilies: ["TECHNICAL_CONSULTANT"],
    travel: {
      type: "INTERNATIONAL_TRAVEL",
      percentage: 20,
      percentageRange: "10-20%",
      destinations: ["Europe", "USA"],
      evidence: "Global customer implementation travel to Frankfurt & New York (20% travel).",
      notes: "Global customer implementation travel to Frankfurt & New York.",
    },
    description:
      "Consult on enterprise content models, composable frontends, and integration middleware for omnichannel commerce platforms.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-004",
    postedAt: "2026-09-20T11:00:00Z",
    discoveredAt: "2026-09-24T03:00:00Z",
    lastVerifiedAt: "2026-09-24T03:00:00Z",
    freshness: "RECENT",
    postedDaysAgo: 4,
    status: "SCREENING",
    appliedAt: "2026-09-21T09:00:00Z",
    notes: "Recruiter screening completed. Positive feedback on Contentful & Next.js architecture.",
    nextStep: "Technical round with Principal Consultant scheduled.",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-005",
    title: "Technical Consultant / Implementation Specialist",
    company: "Slalom (Demo)",
    location: "Remote India",
    rawLocation: "Remote India",
    remoteType: "REMOTE",
    isIndiaEligible: true,
    indiaEligibilityReason: "Explicitly designated as India Remote",
    salaryState: "SALARY_NOT_DISCLOSED",
    salaryMin: undefined,
    salaryMax: undefined,
    currency: "INR",
    salaryLpaMin: undefined,
    salaryLpaMax: undefined,
    salaryDisclosed: false,
    isSalaryEstimated: false,
    seniority: "LEAD",
    seniorityEvidence: "Lead consultant (12+ yrs exp)",
    experienceMin: 12,
    experienceMax: 17,
    skills: ["TypeScript", "React", "Angular", "Enterprise Integration", "Cloud (AWS/GCP)"],
    roleFamily: "TECHNICAL_CONSULTANT",
    secondaryRoleFamilies: ["IMPLEMENTATION_CONSULTANT"],
    travel: {
      type: "CLIENT_SITE_TRAVEL",
      percentage: 15,
      percentageRange: "10-20%",
      destinations: ["USA"],
      evidence: "Periodic client site visits for discovery phases (approx 15%).",
      notes: "Client site visits for discovery phases.",
    },
    description:
      "Lead enterprise client delivery, system integration, and frontend engineering best practices. High competitive compensation based on expertise.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-005",
    postedAt: "2026-09-19T16:00:00Z",
    discoveredAt: "2026-09-24T02:00:00Z",
    lastVerifiedAt: "2026-09-24T02:00:00Z",
    freshness: "RECENT",
    postedDaysAgo: 5,
    status: "DISCOVERED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
];

export const demoSeedJobs: Job[] = rawDemoJobs.map((raw) => {
  const normTitle = raw.title.toLowerCase().replace(/[^a-z0-9]/g, "");
  const normComp = raw.company.toLowerCase().replace(/[^a-z0-9]/g, "");
  const normalizedLocation = classifyLocation(raw.location, raw.remoteType);
  const match = evaluateJobMatch(
    {
      title: raw.title,
      company: raw.company,
      location: raw.location,
      remoteType: raw.remoteType,
      skills: raw.skills,
      roleFamily: raw.roleFamily,
      seniority: raw.seniority,
      experienceMin: raw.experienceMin,
      experienceMax: raw.experienceMax,
      salaryLpaMin: raw.salaryLpaMin,
      salaryDisclosed: raw.salaryDisclosed,
      travelType: raw.travel.type,
      travelPercentage: raw.travel.percentage,
      travelDestinations: raw.travel.destinations,
      travelEvidence: raw.travel.evidence,
      description: raw.description,
    },
    defaultSearchProfile
  );

  return {
    ...raw,
    normalizedTitle: normTitle,
    normalizedCompany: normComp,
    normalizedLocation,
    actualJobTechnologies: raw.skills,
    matchedTargetTechnologies: match.breakdown.technologyMatch.details
      ?.filter((d) => d.matched)
      .map((d) => d.technology) || [],
    technologyMatchDetails: match.breakdown.technologyMatch.details || [],
    sourceTitle: raw.title,
    sourceLocation: raw.location,
    sourceDescription: raw.description,
    sourceSkills: raw.skills,
    domains: match.domainMatches.filter((d) => d.matched && d.domain !== "OTHER").map((d) => d.domain),
    domainMatches: match.domainMatches,
    careerFit: match.careerFit,
    opportunityPriority: calculateOpportunityPriority(match.careerFit || "POSSIBLE", raw.freshness || "RECENT"),
    opportunityPriorityReasons: getOpportunityPriorityReasons(match.careerFit || "POSSIBLE", raw.freshness || "RECENT"),
    match,
  };
});
