import type { Job } from "@/types";
import { evaluateJobMatch } from "./matchingEngine";
import { defaultSearchProfile } from "@/config/defaultProfile";

const rawDemoJobs: Array<Omit<Job, "match" | "normalizedTitle" | "normalizedCompany">> = [
  {
    id: "demo-job-001",
    title: "Senior Technical Lead - Digital Experience & Headless",
    company: "EPAM Systems (Demo)",
    location: "Hyderabad / Remote India",
    remoteType: "HYBRID",
    salaryMin: 3800000,
    salaryMax: 4800000,
    currency: "INR",
    salaryLpaMin: 38,
    salaryLpaMax: 48,
    salaryDisclosed: true,
    experienceMin: 12,
    experienceMax: 16,
    skills: ["React", "Next.js", "TypeScript", "Contentful", "Headless CMS", "GraphQL"],
    roleFamily: "Senior Technical Lead",
    travel: {
      type: "INTERNATIONAL",
      percentage: 20,
      percentageRange: "10-20%",
      destinations: ["USA", "Europe"],
      notes: "International travel required (15-20%) for client workshops in USA & Switzerland.",
      rawMention: "20% international travel to US client sites",
    },
    description:
      "Looking for a Senior Technical Lead to architect headless CMS solutions using Next.js and Contentful for Global 500 clients. Involves cross-border architecture alignment and client visits.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-001",
    postedAt: "2026-09-23T10:00:00Z",
    discoveredAt: "2026-09-24T06:00:00Z",
    status: "DISCOVERED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-002",
    title: "Frontend Architect - Commerce & Micro-frontends",
    company: "Publicis Sapient (Demo)",
    location: "Hyderabad / Bengaluru",
    remoteType: "HYBRID",
    salaryMin: 4200000,
    salaryMax: 5200000,
    currency: "INR",
    salaryLpaMin: 42,
    salaryLpaMax: 52,
    salaryDisclosed: true,
    experienceMin: 12,
    experienceMax: 18,
    skills: ["React", "TypeScript", "Next.js", "Frontend architecture", "Commerce integrations"],
    roleFamily: "Frontend Architect",
    travel: {
      type: "INTERNATIONAL",
      percentage: 25,
      percentageRange: "20-30%",
      destinations: ["Middle East", "Europe"],
      notes: "International project travel to Dubai and London customer headquarters.",
      rawMention: "25% travel to Middle East & UK",
    },
    description:
      "Enterprise digital experience leader seeking a Frontend Architect for composable commerce and digital experience platforms. Lead high-performance engineering teams and advise C-level client stakeholders.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-002",
    postedAt: "2026-09-22T08:30:00Z",
    discoveredAt: "2026-09-24T05:30:00Z",
    status: "SAVED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-003",
    title: "Solutions Architect - Modern Web & Headless CMS",
    company: "Thoughtworks (Demo)",
    location: "Remote from India",
    remoteType: "REMOTE",
    salaryMin: 4000000,
    salaryMax: 5000000,
    currency: "INR",
    salaryLpaMin: 40,
    salaryLpaMax: 50,
    salaryDisclosed: true,
    experienceMin: 11,
    experienceMax: 16,
    skills: ["React", "Angular", "TypeScript", "Contentful", "Design Systems", "Node.js"],
    roleFamily: "Solutions Architect",
    travel: {
      type: "CLIENT_SITE",
      percentage: 15,
      percentageRange: "10-20%",
      destinations: ["Singapore", "Australia"],
      notes: "Client-site travel for quarterly architecture review sprints in Singapore.",
      rawMention: "Quarterly travel to Singapore",
    },
    description:
      "Drive architecture design for modern digital transformation initiatives. Guide cross-functional squads in adopting MACH principles and headless digital experience architectures.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-003",
    postedAt: "2026-09-21T14:15:00Z",
    discoveredAt: "2026-09-24T04:00:00Z",
    status: "APPLIED",
    appliedAt: "2026-09-23T11:00:00Z",
    notes: "Applied via referral through senior director. Portfolio shared.",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-004",
    title: "CMS & Digital Experience Consultant",
    company: "Valtech (Demo)",
    location: "Hyderabad / Remote",
    remoteType: "REMOTE",
    salaryMin: 3600000,
    salaryMax: 4600000,
    currency: "INR",
    salaryLpaMin: 36,
    salaryLpaMax: 46,
    salaryDisclosed: true,
    experienceMin: 10,
    experienceMax: 15,
    skills: ["Contentful", "Headless CMS", "React", "Next.js", "Commerce integrations"],
    roleFamily: "CMS / Digital Experience Consultant",
    travel: {
      type: "INTERNATIONAL",
      percentage: 20,
      percentageRange: "10-20%",
      destinations: ["Europe", "USA"],
      notes: "Global customer implementation travel to Frankfurt & New York.",
    },
    description:
      "Consult on enterprise content models, composable frontends, and integration middleware for omnichannel commerce platforms.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-004",
    postedAt: "2026-09-20T11:00:00Z",
    discoveredAt: "2026-09-24T03:00:00Z",
    status: "SCREENING",
    appliedAt: "2026-09-21T09:00:00Z",
    notes: "Recruiter screening completed. Positive feedback on Contentful & Next.js architecture.",
    nextStep: "Technical round with Principal Consultant scheduled.",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "demo-job-005",
    title: "Technical Consultant / Implementation Specialist",
    company: "Slalom (Demo)",
    location: "International Remote / India",
    remoteType: "REMOTE",
    salaryMin: undefined,
    salaryMax: undefined,
    currency: "INR",
    salaryLpaMin: undefined,
    salaryLpaMax: undefined,
    salaryDisclosed: false, // Disclosed = false: should be surfaced per rule: "never reject solely because salary is unknown"
    experienceMin: 12,
    experienceMax: 17,
    skills: ["TypeScript", "React", "Angular", "Enterprise Integration Consultant", "AWS"],
    roleFamily: "Technical Consultant",
    travel: {
      type: "CLIENT_SITE",
      percentage: 15,
      percentageRange: "10-20%",
      destinations: ["USA"],
      notes: "Client site visits for discovery phases.",
    },
    description:
      "Lead enterprise client delivery, system integration, and frontend engineering best practices. High competitive compensation based on expertise.",
    source: "[DEMO DATA - Sample Verification Listing]",
    url: "https://example.com/demo-careers/job-005",
    postedAt: "2026-09-19T16:00:00Z",
    discoveredAt: "2026-09-24T02:00:00Z",
    status: "DISCOVERED",
    isDemo: true,
    updatedAt: new Date().toISOString(),
  },
];

export const demoSeedJobs: Job[] = rawDemoJobs.map((raw) => {
  const normTitle = raw.title.toLowerCase().replace(/[^a-z0-9]/g, "");
  const normComp = raw.company.toLowerCase().replace(/[^a-z0-9]/g, "");
  const match = evaluateJobMatch(
    {
      title: raw.title,
      company: raw.company,
      location: raw.location,
      remoteType: raw.remoteType,
      skills: raw.skills,
      roleFamily: raw.roleFamily,
      experienceMin: raw.experienceMin,
      experienceMax: raw.experienceMax,
      salaryLpaMin: raw.salaryLpaMin,
      salaryDisclosed: raw.salaryDisclosed,
      travelType: raw.travel.type,
      travelPercentage: raw.travel.percentage,
      travelDestinations: raw.travel.destinations,
      description: raw.description,
    },
    defaultSearchProfile
  );

  return {
    ...raw,
    normalizedTitle: normTitle,
    normalizedCompany: normComp,
    match,
  };
});
