import type { SearchProfile } from "@/types";

export const defaultSearchProfile: SearchProfile = {
  experienceYears: 12,
  minSalaryLpa: 35,
  targetLocations: [
    "Hyderabad",
    "India",
    "Remote from India",
    "International Remote",
    "Bengaluru",
    "Pune",
  ],
  targetRoleFamilies: [
    "Senior Technical Lead",
    "Frontend Architect",
    "UI Architect",
    "Digital Experience Architect",
    "Technical Architect",
    "Solutions Architect",
    "Technical Consultant",
    "Implementation Consultant",
    "Professional Services Engineer",
    "Solutions Engineer",
    "Enterprise Integration Consultant",
    "CMS / Digital Experience Consultant",
    "Commerce Consultant",
  ],
  targetSkills: [
    "React",
    "Next.js",
    "TypeScript",
    "Angular",
    "Contentful",
    "Headless CMS",
    "Digital Experience",
    "Frontend architecture",
    "Commerce integrations",
    "Node.js",
    "GraphQL",
    "Design Systems",
  ],
  preferredTravelTypes: [
    "INTERNATIONAL_TRAVEL",
    "CLIENT_SITE_TRAVEL",
    "RELOCATION",
  ],
  preferredTravelDestinations: [
    "USA",
    "Europe",
    "Middle East",
    "Singapore",
    "United Kingdom",
    "Germany",
    "UAE",
  ],
  preferredRemoteTypes: ["REMOTE", "HYBRID"],
  enabledProviders: ["remotive", "arbeitnow", "greenhouse", "jobicy", "adzuna"],
};
